{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import dash_bootstrap_components as dbc\n",
    "\n",
    "import dash\n",
    "dash.__version__\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from dash.dependencies import Input, Output,State\n",
    "\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from plotly import tools"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>COUNTRY</th>\n",
       "      <th>CODE</th>\n",
       "      <th>Confirm cases</th>\n",
       "      <th>Deaths</th>\n",
       "      <th>Recovered</th>\n",
       "      <th>Active</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>AFG</td>\n",
       "      <td>233861</td>\n",
       "      <td>1385</td>\n",
       "      <td>28016</td>\n",
       "      <td>8552.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Albania</td>\n",
       "      <td>ALB</td>\n",
       "      <td>5667112</td>\n",
       "      <td>245</td>\n",
       "      <td>4184</td>\n",
       "      <td>3846.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Algeria</td>\n",
       "      <td>DZA</td>\n",
       "      <td>3044940</td>\n",
       "      <td>1424</td>\n",
       "      <td>28874</td>\n",
       "      <td>10770.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Andorra</td>\n",
       "      <td>AND</td>\n",
       "      <td>3582362</td>\n",
       "      <td>53</td>\n",
       "      <td>875</td>\n",
       "      <td>117.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Angola</td>\n",
       "      <td>AGO</td>\n",
       "      <td>386054</td>\n",
       "      <td>94</td>\n",
       "      <td>814</td>\n",
       "      <td>1226.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       COUNTRY CODE  Confirm cases  Deaths  Recovered   Active\n",
       "0  Afghanistan  AFG         233861    1385      28016   8552.0\n",
       "1      Albania  ALB        5667112     245       4184   3846.0\n",
       "2      Algeria  DZA        3044940    1424      28874  10770.0\n",
       "3      Andorra  AND        3582362      53        875    117.0\n",
       "4       Angola  AGO         386054      94        814   1226.0"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "world_con=pd.read_csv('../data/processed/COVID_CRD.csv',sep=';')\n",
    "world_con.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>COUNTRY</th>\n",
       "      <th>CODE</th>\n",
       "      <th>Confirm cases</th>\n",
       "      <th>Deaths</th>\n",
       "      <th>Recovered</th>\n",
       "      <th>Active</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>AFG</td>\n",
       "      <td>233861</td>\n",
       "      <td>1385</td>\n",
       "      <td>28016</td>\n",
       "      <td>8552.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Albania</td>\n",
       "      <td>ALB</td>\n",
       "      <td>5667112</td>\n",
       "      <td>245</td>\n",
       "      <td>4184</td>\n",
       "      <td>3846.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Algeria</td>\n",
       "      <td>DZA</td>\n",
       "      <td>3044940</td>\n",
       "      <td>1424</td>\n",
       "      <td>28874</td>\n",
       "      <td>10770.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Andorra</td>\n",
       "      <td>AND</td>\n",
       "      <td>3582362</td>\n",
       "      <td>53</td>\n",
       "      <td>875</td>\n",
       "      <td>117.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Angola</td>\n",
       "      <td>AGO</td>\n",
       "      <td>386054</td>\n",
       "      <td>94</td>\n",
       "      <td>814</td>\n",
       "      <td>1226.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       COUNTRY CODE  Confirm cases  Deaths  Recovered   Active\n",
       "0  Afghanistan  AFG         233861    1385      28016   8552.0\n",
       "1      Albania  ALB        5667112     245       4184   3846.0\n",
       "2      Algeria  DZA        3044940    1424      28874  10770.0\n",
       "3      Andorra  AND        3582362      53        875    117.0\n",
       "4       Angola  AGO         386054      94        814   1226.0"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_input_large=pd.read_csv('../data/processed/COVID_CRD.csv',sep=';')\n",
    "df_input_large.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "positional argument follows keyword argument (<ipython-input-31-c286c81191ba>, line 25)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-31-c286c81191ba>\"\u001b[1;36m, line \u001b[1;32m25\u001b[0m\n\u001b[1;33m    figure.update_layout(title=dict(font=dict(size=28),x=0.5,xanchor='center'),\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m positional argument follows keyword argument\n"
     ]
    }
   ],
   "source": [
    "app = dash.Dash(__name__)\n",
    "\n",
    "\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H1(\"World Map\"),\n",
    "    \n",
    "    dcc.RadioItems(id = 'Items',\n",
    "    options=[\n",
    "        {'label': 'Confirmed', 'value': 'Confirm cases'},\n",
    "        {'label': 'Death', 'value': 'Deaths'},\n",
    "        {'label': 'Recovered', 'value': 'Recovered'}\n",
    "    ],\n",
    "    value='Death'\n",
    "                ),\n",
    "    \n",
    "    dcc.Graph(id = \"World_map\",\n",
    "            figure = px.choropleth(df, locations='CODE',\n",
    "                            color= cases,\n",
    "                            hover_name=\"COUNTRY\",\n",
    "                            projection='natural earth',\n",
    "                            title='World map',\n",
    "                            color_continuous_scale=px.colors.sequential.Plasma),\n",
    "\n",
    "            figure.update_layout(title=dict(font=dict(size=28),x=0.5,xanchor='center'),\n",
    "                          margin=dict(l=60, r=60, t=50, b=50))\n",
    "    )\n",
    "])\n",
    "\n",
    "fig.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.callback(\n",
    "    Output('World_map', 'figure'),\n",
    "    [Input('Items', 'value')])\n",
    "\n",
    "def World(cases):\n",
    "    df = df_input_large\n",
    "    \n",
    "    fig = px.choropleth(df, locations='CODE',\n",
    "                            color= cases,\n",
    "                            hover_name=\"COUNTRY\",\n",
    "                            projection='natural earth',\n",
    "                            title='World map',\n",
    "                            color_continuous_scale=px.colors.sequential.Plasma)\n",
    "\n",
    "    fig.update_layout(title=dict(font=dict(size=28),x=0.5,xanchor='center'),\n",
    "                          margin=dict(l=60, r=60, t=50, b=50))\n",
    "    \n",
    "    \n",
    "    \n",
    "    return (fig)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:4050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:4050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:4050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:4050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:4050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:4050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:4050/\n",
      "\n",
      " Warning: This is a development server. Do not use app.run_server\n",
      " Warning: This is a development server. Do not use app.run_server\n",
      " Warning: This is a development server. Do not use app.run_server\n",
      " Warning: This is a development server. Do not use app.run_server\n",
      " Warning: This is a development server. Do not use app.run_server\n",
      " Warning: This is a development server. Do not use app.run_server\n",
      " Warning: This is a development server. Do not use app.run_server\n",
      " in production, use a production WSGI server like gunicorn instead.\n",
      "\n",
      " in production, use a production WSGI server like gunicorn instead.\n",
      "\n",
      " in production, use a production WSGI server like gunicorn instead.\n",
      "\n",
      " in production, use a production WSGI server like gunicorn instead.\n",
      "\n",
      " in production, use a production WSGI server like gunicorn instead.\n",
      "\n",
      " in production, use a production WSGI server like gunicorn instead.\n",
      "\n",
      " in production, use a production WSGI server like gunicorn instead.\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:4050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [27/Aug/2020 14:39:00] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [27/Aug/2020 14:39:00] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [27/Aug/2020 14:39:00] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [27/Aug/2020 14:39:01] \"\u001b[37mGET /_favicon.ico?v=1.14.0 HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1050, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 985, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-25-7f14479ca007>\", line 34, in World\n",
      "    color_continuous_scale=px.colors.sequential.Plasma)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_chart_types.py\", line 975, in choropleth\n",
      "    else geojson.__geo_interface__,\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1831, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1364, in build_dataframe\n",
      "    args, wide_mode, var_name, value_name\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1166, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'color' is not the name of a column in 'data_frame'. Expected one of ['COUNTRY', 'CODE', 'Confirm cases', 'Deaths', 'Recovered', 'Active'] but received: Death\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1050, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 985, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-25-7f14479ca007>\", line 34, in World\n",
      "    color_continuous_scale=px.colors.sequential.Plasma)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_chart_types.py\", line 975, in choropleth\n",
      "    else geojson.__geo_interface__,\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1831, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1364, in build_dataframe\n",
      "    args, wide_mode, var_name, value_name\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1166, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'color' is not the name of a column in 'data_frame'. Expected one of ['COUNTRY', 'CODE', 'Confirm cases', 'Deaths', 'Recovered', 'Active'] but received: Death\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1050, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 985, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-25-7f14479ca007>\", line 34, in World\n",
      "    color_continuous_scale=px.colors.sequential.Plasma)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_chart_types.py\", line 975, in choropleth\n",
      "    else geojson.__geo_interface__,\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1831, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1364, in build_dataframe\n",
      "    args, wide_mode, var_name, value_name\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1166, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'color' is not the name of a column in 'data_frame'. Expected one of ['COUNTRY', 'CODE', 'Confirm cases', 'Deaths', 'Recovered', 'Active'] but received: Death\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1050, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 985, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-25-7f14479ca007>\", line 34, in World\n",
      "    color_continuous_scale=px.colors.sequential.Plasma)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_chart_types.py\", line 975, in choropleth\n",
      "    else geojson.__geo_interface__,\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1831, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1364, in build_dataframe\n",
      "    args, wide_mode, var_name, value_name\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1166, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'color' is not the name of a column in 'data_frame'. Expected one of ['COUNTRY', 'CODE', 'Confirm cases', 'Deaths', 'Recovered', 'Active'] but received: Death\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1050, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 985, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-25-7f14479ca007>\", line 34, in World\n",
      "    color_continuous_scale=px.colors.sequential.Plasma)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_chart_types.py\", line 975, in choropleth\n",
      "    else geojson.__geo_interface__,\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1831, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1364, in build_dataframe\n",
      "    args, wide_mode, var_name, value_name\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1166, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'color' is not the name of a column in 'data_frame'. Expected one of ['COUNTRY', 'CODE', 'Confirm cases', 'Deaths', 'Recovered', 'Active'] but received: Death\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1050, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 985, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-25-7f14479ca007>\", line 34, in World\n",
      "    color_continuous_scale=px.colors.sequential.Plasma)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_chart_types.py\", line 975, in choropleth\n",
      "    else geojson.__geo_interface__,\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1831, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1364, in build_dataframe\n",
      "    args, wide_mode, var_name, value_name\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1166, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'color' is not the name of a column in 'data_frame'. Expected one of ['COUNTRY', 'CODE', 'Confirm cases', 'Deaths', 'Recovered', 'Active'] but received: Death\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1050, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 985, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-25-7f14479ca007>\", line 34, in World\n",
      "    color_continuous_scale=px.colors.sequential.Plasma)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_chart_types.py\", line 975, in choropleth\n",
      "    else geojson.__geo_interface__,\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1831, in make_figure\n",
      "    args = build_dataframe(args, constructor)\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1364, in build_dataframe\n",
      "    args, wide_mode, var_name, value_name\n",
      "  File \"C:\\Users\\Vishal Sharbidar\\anaconda3\\lib\\site-packages\\plotly\\express\\_core.py\", line 1166, in process_args_into_dataframe\n",
      "    raise ValueError(err_msg)\n",
      "ValueError: Value of 'color' is not the name of a column in 'data_frame'. Expected one of ['COUNTRY', 'CODE', 'Confirm cases', 'Deaths', 'Recovered', 'Active'] but received: Death\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [27/Aug/2020 14:39:01] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "if __name__ == '__main__':\n",
    "    app.run_server(port=4050)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig = go.Figure(go.Choropleth(\n",
    "                    locations = df['CODE'],\n",
    "                    z = df[cases],\n",
    "                    text = df['COUNTRY'],\n",
    "                    colorscale = 'Blues',\n",
    "                    autocolorscale=False,\n",
    "                    reversescale=False,\n",
    "                    marker_line_color='darkgray',\n",
    "                    marker_line_width=0.5,\n",
    "                    colorbar_title = 'Confirmed cases',\n",
    "                    ))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
